version: '3.1'

services:

  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - 443:443

  mariadb:
    build: requirements/mariadb
    env_file: .env
    container_name: mariadb

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    container_name: wordpress
