version: '3.1'

services:

  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
        - 80:80
        - 443:443
    restart: always
    hostname: agutierr.42.fr
    domainname: agutierr.42.fr
    networks:
        docker-network:
            aliases:
                - agutierr.42.fr 

networks:
    docker-network:
        name: inception_net
        driver: bridge
